platform :ios, '14.0'

use_frameworks!

target 'AmazingDelegateCommandExample' do
  project 'AmazingDelegateCommandExample.xcodeproj'
  
  pod 'AmazingDelegateCommand', :path => '../'
  
  pod 'SnapKit', '5.0.1'
end
